### ISSUE TITLE
File named 'eng.traineddata' created after the process done

### ISSUE THREAD

**Issue by zulhfreelancer** [Arthelon/imgclip#6]
I noticed that a file named 'eng.traineddata' created after I ran the image recognition command ie:

```
~/Desktop ᐅ imgclip k.jpg -l eng
pre-main prep time: 79 ms
recognizing [====================================================] 100% 4.3s
Finished copying to clipboard!
```

Is this expected?

**Comment by Arthelon** [comment]
@zulhfreelancer Thanks for pointing this out. The tesseract.js wrapper requires language data files to perform the recognition and pulls it down into the current working directory if it isn't already there. Unfortunately, the wrapper API doesn't seem to offer an option for inserting filepaths to language data files. 

I'll add a note into the README and a flag for cleaning up the language file for now. I don't think cleaning up the data file should be default behaviour since there's a hefty performance cost in downloading the file on each execution of the command.

**Comment by Arthelon** [comment]
c8c93f750f53fb7f3b136832df2ac032774b5ef4
